name: 星光的个人博客
author: devzld
url: https://devzld.github.io
destination: docs
baseurl:
cdnurl: https://cdn.jsdelivr.net/gh/devzld/devzld.github.io@2b289aa352a84f79fade0713c903c5d18532de8c
resume_site: https://devzld.github.io
description: 个人博客
github_username: devzld
github: https://github.com/devzld
plugins: [jekyll-paginate]
permalink: /:year-:month-:day-:title
paginate: 12
paginate_path: "/page/:num/"
exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']
highlighter: rouge
markdown: kramdown
comments :
  gitalk :
    clientID : 1ed81ffadee7491d960d
    clientSecret : 23951794a420ad09070199a1da082aa8f69574f9
    repo : devzld.github.io
    owner : devzld
    admin : 'devzld'
